# Generated by Django 5.2.3 on 2025-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='fields',
            field=models.TextField(default={'1': 'None'}),
            preserve_default=False,
        ),
    ]
